/**
 * 專案 CLAUDE.md 部署 — 寫入 ~/.claude/projects/{path-encoded}/CLAUDE.md
 *
 * Claude Code 原生支持 ~/.claude/projects/ 目錄，
 * 根據當前工作目錄自動匹配對應的 CLAUDE.md。
 */

import fs from 'fs'
import path from 'path'
import { encodeProjectPath } from '../config-classifier.mjs'

const HOME = process.env.HOME
const PROJECTS_DIR = path.join(HOME, '.claude', 'projects')

const GENERATED_MARKER = '# Generated by ab-dotfiles — DO NOT EDIT manually\n'

/**
 * 部署單個 repo 的 CLAUDE.md
 *
 * @param {string} localPath - repo 本機路徑
 * @param {string} claudeMdContent - CLAUDE.md 內容
 * @returns {{ deployed: boolean, path: string, skipped?: string }}
 */
export function deployProjectClaudeMd(localPath, claudeMdContent) {
  if (!localPath || !claudeMdContent) {
    return { deployed: false, path: '', skipped: 'no content' }
  }

  const encoded = encodeProjectPath(localPath)
  const projectDir = path.join(PROJECTS_DIR, encoded)
  const claudeMdPath = path.join(projectDir, 'CLAUDE.md')

  // 檢查是否已有用戶手寫的 CLAUDE.md（不帶 GENERATED_MARKER）
  if (fs.existsSync(claudeMdPath)) {
    const existing = fs.readFileSync(claudeMdPath, 'utf8')
    if (!existing.startsWith(GENERATED_MARKER)) {
      return { deployed: false, path: claudeMdPath, skipped: '用戶自訂' }
    }
  }

  fs.mkdirSync(projectDir, { recursive: true })
  fs.writeFileSync(claudeMdPath, GENERATED_MARKER + claudeMdContent)

  return { deployed: true, path: claudeMdPath }
}

/**
 * 批量部署多個 repo 的 CLAUDE.md
 *
 * @param {Array<{ localPath: string, content: string, repo: string }>} items
 * @returns {{ deployed: string[], skipped: string[] }}
 */
export function deployAllProjectClaudeMd(items) {
  const deployed = []
  const skipped = []

  for (const { localPath, content, repo } of items) {
    const result = deployProjectClaudeMd(localPath, content)
    if (result.deployed) {
      deployed.push(repo)
    } else if (result.skipped) {
      skipped.push(`${repo}（${result.skipped}）`)
    }
  }

  return { deployed, skipped }
}
