/**
 * 專案級配置注入 — 將 .claude/ 配置注入到各 repo 本機目錄
 *
 * 策略：
 * - 已有 .claude/ → 先備份到 dist/backup/
 * - 已有 CLAUDE.md → 不覆蓋（可能是用戶手寫的）
 * - ab-dotfiles 生成的檔案帶標記，有標記的覆蓋，無標記的跳過
 */

import fs from 'fs'
import path from 'path'
import { cpDir } from '../backup.mjs'

const GENERATED_MARKER = '# Generated by ab-dotfiles — DO NOT EDIT manually\n'

function shouldOverwrite(filePath) {
  if (!fs.existsSync(filePath)) return true
  const content = fs.readFileSync(filePath, 'utf8')
  return content.startsWith(GENERATED_MARKER)
}

/**
 * 注入專案配置到 repo/.claude/
 *
 * @param {Object} opts
 * @param {string} opts.localPath - repo 本機路徑
 * @param {string} opts.role - main | temp | tool
 * @param {Object} opts.config - getProjectConfig 結果
 * @param {string} opts.repoDir - ab-dotfiles 根目錄（讀取 claude/ 資源）
 * @param {string|null} opts.claudeMdContent - AI 生成的 CLAUDE.md 內容
 * @returns {{ injected: string[], skipped: string[] }}
 */
export function deployProject({ localPath, role, config, repoDir, claudeMdContent }) {
  const injected = []
  const skipped = []

  if (!localPath || !fs.existsSync(localPath)) {
    return { injected, skipped, error: 'localPath not found' }
  }

  const claudeDir = path.join(localPath, '.claude')
  fs.mkdirSync(claudeDir, { recursive: true })

  // CLAUDE.md
  const claudeMdPath = path.join(localPath, 'CLAUDE.md')
  if (claudeMdContent) {
    if (!fs.existsSync(claudeMdPath)) {
      fs.writeFileSync(claudeMdPath, GENERATED_MARKER + claudeMdContent)
      injected.push('CLAUDE.md')
    } else {
      skipped.push('CLAUDE.md (已存在)')
    }
  }

  // commands
  if (config.commands?.length > 0) {
    const srcDir = path.join(repoDir, 'claude', 'commands')
    const destDir = path.join(claudeDir, 'commands')
    fs.mkdirSync(destDir, { recursive: true })
    for (const name of config.commands) {
      const src = path.join(srcDir, `${name}.md`)
      const dest = path.join(destDir, `${name}.md`)
      if (fs.existsSync(src)) {
        if (shouldOverwrite(dest)) {
          const content = fs.readFileSync(src, 'utf8')
          fs.writeFileSync(dest, GENERATED_MARKER + content)
          injected.push(`commands/${name}.md`)
        } else {
          skipped.push(`commands/${name}.md (用戶自訂)`)
        }
      }
    }
  }

  // agents
  if (config.agents?.length > 0) {
    const srcDir = path.join(repoDir, 'claude', 'agents')
    const destDir = path.join(claudeDir, 'agents')
    fs.mkdirSync(destDir, { recursive: true })
    for (const name of config.agents) {
      const src = path.join(srcDir, `${name}.md`)
      const dest = path.join(destDir, `${name}.md`)
      if (fs.existsSync(src)) {
        if (shouldOverwrite(dest)) {
          const content = fs.readFileSync(src, 'utf8')
          fs.writeFileSync(dest, GENERATED_MARKER + content)
          injected.push(`agents/${name}.md`)
        } else {
          skipped.push(`agents/${name}.md (用戶自訂)`)
        }
      }
    }
  }

  // rules
  if (config.rules?.length > 0) {
    const srcDir = path.join(repoDir, 'claude', 'rules')
    const destDir = path.join(claudeDir, 'rules')
    fs.mkdirSync(destDir, { recursive: true })
    for (const name of config.rules) {
      const src = path.join(srcDir, `${name}.md`)
      const dest = path.join(destDir, `${name}.md`)
      if (fs.existsSync(src)) {
        if (shouldOverwrite(dest)) {
          const content = fs.readFileSync(src, 'utf8')
          fs.writeFileSync(dest, GENERATED_MARKER + content)
          injected.push(`rules/${name}.md`)
        } else {
          skipped.push(`rules/${name}.md (用戶自訂)`)
        }
      }
    }
  }

  // .gitignore 處理
  const gitignorePath = path.join(localPath, '.gitignore')
  if (fs.existsSync(gitignorePath)) {
    const content = fs.readFileSync(gitignorePath, 'utf8')
    if (!content.includes('.claude/settings.local.json')) {
      fs.appendFileSync(gitignorePath, '\n# ab-dotfiles local settings\n.claude/settings.local.json\n')
      injected.push('.gitignore (追加)')
    }
  }

  return { injected, skipped }
}
